# Generated by Django 3.0.6 on 2020-07-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('f', 'fruits'), ('v', 'vegitables'), ('j', 'juice')], max_length=100)),
                ('offer', models.BooleanField(default=False)),
                ('offer_percentage', models.IntegerField()),
                ('offer_price', models.IntegerField()),
            ],
        ),
    ]
